name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Verify files exist
      run: |
        ls -la
        [ -f index.html ] || { echo "index.html missing"; exit 1; }
        [ -f styles.css ] || { echo "style.css missing"; exit 1; }
        [ -f script.js ] || { echo "script.js missing"; exit 1; }
        echo "All required files present"
    
    - name: Setup Pages
      uses: actions/configure-pages@v3
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./
    
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2