name: Frontend Deployment

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is crucial for GitHub Pages deployment
      pages: write
      id-token: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Verify files
      run: |
        [ -f index.html ] && echo "index.html exists" || exit 1
        [ -f styles.css ] && echo "style.css exists" || exit 1
        [ -f script.js ] && echo "script.js exists" || exit 1
        
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./
        
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2